if(CMAKE_HELPERS_BUILD_OPTIONS_INCLUDED)
    return()
endif()
set(CMAKE_HELPERS_BUILD_OPTIONS_INCLUDED TRUE)

include(${CMAKE_CURRENT_LIST_DIR}/tidy.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/cppcheck.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/include_what_you_use.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/cpplint.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/sanitizer.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/compiler_args.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/compiler_warning_flags.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/stdlib.cmake)

set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
mark_as_advanced(CMAKE_INSTALL_PREFIX)

function(target_add_default_build_options target scope)
    target_add_tidy_flags(${target} ${scope})
    target_add_cppcheck_flags(${target} ${scope})
    target_add_include_what_you_use_flags(${target} ${scope})
    target_add_cpplint_flags(${target} ${scope})
    target_add_warning_flags(${target} ${scope})
    target_add_sanitizer_flags(${target} ${scope})
    target_add_stdlib_flags(${target} ${scope})
    target_add_stdlib_debug_flags(${target} ${scope})
    target_add_optimizer_flags(${target} ${scope})
endfunction()
