function(configure_host_build)

    cmake_parse_arguments(PARSE_ARGV 0 PARSED_ARGS "CLEAR_ENV" "" "")

    set(all_targets ${PARSED_ARGS_UNPARSED_ARGUMENTS})
    list(GET all_targets 0 primary_target)

    set(extra_args)
    if(${CMAKE_VERSION} VERSION_GREATER_EQUAL "3.19.0")
        set(extra_args COMMAND_ERROR_IS_FATAL ANY)
    endif()

    if(PARSED_ARGS_CLEAR_ENV)
        unset(ENV{CC})
        unset(ENV{CXX})
    endif()

    set(build_dir ${CMAKE_CURRENT_BINARY_DIR}/${primary_target}_host_build)
    set(cmake_extra_args "-G${CMAKE_GENERATOR}")

    set(preload_file ${build_dir}/preload.cmake)
    file(MAKE_DIRECTORY ${build_dir})
    file(WRITE ${preload_file} "# Autogenerated preload for host build\n")

    get_cmake_property(all_variables CACHE_VARIABLES)
    foreach(variable_name ${all_variables})
        if(variable_name MATCHES "^USE"
           OR variable_name MATCHES "^CMAKE_BUILD_TYPE"
           OR variable_name MATCHES "^FETCHCONTENT_SOURCE_DIR_")

            get_property(
                var_type
                CACHE ${variable_name}
                PROPERTY TYPE)
            if(NOT var_type)
                set(var_type STRING)
            endif()

            file(APPEND ${preload_file} "set(${variable_name} \"${${variable_name}}\" CACHE ${var_type} \"\")\n")
        endif()
    endforeach()

    execute_process(
        COMMAND ${CMAKE_COMMAND} -C ${preload_file} -S ${CMAKE_CURRENT_LIST_DIR} -B ${build_dir} ${cmake_extra_args}
        WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
        RESULT_VARIABLE STATUS ${extra_args})

    if(STATUS AND NOT STATUS EQUAL 0)
        message(FATAL_ERROR "configuring ${primary_target} failed!")
    endif()

    add_custom_target(
        ${primary_target}_clean
        COMMAND ${CMAKE_COMMAND} --build ${build_dir} --target clean
        COMMENT "Cleaning host build: ${primary_target}")

    foreach(target IN LISTS all_targets)
        add_custom_target(
            ${target}
            COMMAND ${CMAKE_COMMAND} --build ${build_dir} --target ${target}
            WORKING_DIRECTORY ${build_dir}
            BYPRODUCTS ${build_dir}/${target}
            COMMENT "Building host tool: ${target}")
        set_target_properties(${target} PROPERTIES HOST_EXECUTABLE_PATH ${build_dir}/${target})
    endforeach()

endfunction()
